# Generated by Selenium IDE
from selenium.webdriver.chrome.options import Options
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSmokeTest():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless=new")
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1Navigatetothehomepage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
    assert self.driver.title == "Teton Idaho CoC"
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
    assert len(elements) > 0
  
  def test_2Navigatetothehomepage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
    self.driver.set_window_size(1336, 1032)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1 img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2 img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "Join Us")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Join Us").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.text_to_be_present_in_element((By.CSS_SELECTOR, "section > h3"), "Welcome to the Teton Chamber of Commerce Signup Wizard!"))
  
  def test_3Navigatetothehomepage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/directory.html")
    self.driver.set_window_size(1339, 1032)
    self.driver.find_element(By.ID, "directory-grid").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
    self.driver.find_element(By.ID, "directory-list").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
  
  def test_4Navigatetothejoinpage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/join.html")
    self.driver.set_window_size(1334, 1032)

    fname = WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.NAME, "fname"))
    )
    assert fname.is_displayed()

    fname.clear()
    fname.send_keys("testfirst")

    lname = self.driver.find_element(By.NAME, "lname")
    lname.clear()
    lname.send_keys("testlast")

    bizname = self.driver.find_element(By.NAME, "bizname")
    bizname.clear()
    bizname.send_keys("testbusiness")

    biztitle = self.driver.find_element(By.NAME, "biztitle")
    biztitle.clear()
    biztitle.send_keys("testtitle")

    self.driver.find_element(By.NAME, "submit").click()

    WebDriverWait(self.driver, 30).until(
        expected_conditions.presence_of_element_located((By.NAME, "email"))
    )
  
  
  def test_5Navigatetotheadminpage(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/admin.html")
    self.driver.set_window_size(1335, 1032)

    username = WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.ID, "username"))
    )
    assert username.is_displayed()

    username.clear()
    username.send_keys("asdasda")

    password = self.driver.find_element(By.ID, "password")
    password.clear()
    password.send_keys("asdasda")

    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()

    WebDriverWait(self.driver, 30).until(
        expected_conditions.text_to_be_present_in_element(
            (By.CSS_SELECTOR, ".errorMessage"),
            "Invalid username and password."
        )
    )
  
